import './globals.css'
import type { Metadata } from 'next'
import { Public_Sans } from 'next/font/google'
import Header from './components/Header'
import Footer from './components/Footer'

const public_sans = Public_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        // <html lang='en' className={`desktop:text-[14px] phone:text-[12px]`}>
        <html lang='en'>
            <head>
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <title>MLMH Shop</title>
            </head>
            <body
                className={`${public_sans.className} min-h-screen flex flex-col`}
            >
                <Header />
                <div className='flex-grow flex'>{children}</div>
                <Footer />
            </body>
        </html>
    )
}
