// import './polyfills'
import './globals.css'
import type { Metadata } from 'next'
import { Public_Sans } from 'next/font/google'
import Footer from './components/Footer'
import dynamic from 'next/dynamic'

const public_sans = Public_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const DynamicHeader = dynamic(() => import('./components/Header'), {
    loading: () => <p>Loading...</p>,
    ssr: false,
})

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <head>
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <title>MLMH Shop</title>
            </head>
            <body
                className={`${public_sans.className} min-h-screen flex flex-col`}
            >
                <DynamicHeader />
                <div className='flex flex-grow'>{children}</div>
                <Footer />
            </body>
        </html>
    )
}
