# Production Swarm configuration
services:
    mlmh_shop:
        build:
            target: production
        image: thegobc/mlmh_shop:latest
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.mlmh_shop.rule=Host(`mlmhshop.gobc.fr`)'
            - 'traefik.http.routers.mlmh_shop.entrypoints=websecure'
            - 'traefik.http.routers.mlmh_shop.tls.certresolver=myresolver'
            - 'traefik.http.services.mlmh_shop.loadbalancer.server.port=3000'
        secrets:
            - DATABASE_URL
            - STRIPE_SECRET_KEY
            - BREVO_API_KEY
            - STRIPE_WEBHOOK_SECRET
        environment:
            NODE_ENV: production
            NEXT_PUBLIC_BASE_URL: https://mlmhshop.gobc.fr
            NEXT_PUBLIC_API_URL: https://mlmhshop.gobc.fr
            NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_live_51OP5EJGPIxCEDLOvx9Hmpi6kPEkEIu5fXfyZDy2tk8Sayjtt8P7xqhExLdehnPPZcFYm1ZSuij1iFx3teqiNncVE00qADmtYRw
        networks:
            - webnet

secrets:
    DATABASE_URL:
        external: true
    STRIPE_SECRET_KEY:
        external: true
    BREVO_API_KEY:
        external: true
    STRIPE_WEBHOOK_SECRET:
        external: true

networks:
    webnet:
        external: true
