services:
    mlmh_shop_app:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        environment:
            NODE_ENV: development
            NEXT_PUBLIC_API_URL: http://localhost:3000
